package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnnotatedDocument generated by hbm2java
 */
@Entity
@Table(name="annotated_document"
    ,catalog="metaserver2"
)
public class AnnotatedDocument  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private byte[] html;
     private String pmid;
     private Date created;
     private Date modified;

    public AnnotatedDocument() {
    }

	
    public AnnotatedDocument(Project project, byte[] html, String pmid) {
        this.project = project;
        this.html = html;
        this.pmid = pmid;
    }
    public AnnotatedDocument(Project project, byte[] html, String pmid, Date created, Date modified) {
       this.project = project;
       this.html = html;
       this.pmid = pmid;
       this.created = created;
       this.modified = modified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    
    @Column(name="html", nullable=false)
    public byte[] getHtml() {
        return this.html;
    }
    
    public void setHtml(byte[] html) {
        this.html = html;
    }

    
    @Column(name="PMID", nullable=false, length=8)
    public String getPmid() {
        return this.pmid;
    }
    
    public void setPmid(String pmid) {
        this.pmid = pmid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


