package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DocumentTypeTruePositive generated by hbm2java
 */
@Entity
@Table(name="document_type_true_positive"
    ,catalog="metaserver2"
    , uniqueConstraints = @UniqueConstraint(columnNames={"document_id", "prediction_type_id", "gold_type_id", "user_id", "server_version_id", "server_id", "prediction_evaluation_id"}) 
)
public class DocumentTypeTruePositive  implements java.io.Serializable {


     private Integer id;
     private Document document;
     private PredictionEvaluation predictionEvaluation;
     private Server server;
     private ServerVersion serverVersion;
     private Type typeByPredictionTypeId;
     private Type typeByGoldTypeId;
     private User user;
     private Integer truePositives;
     private String goldTruePositivesJson;
     private String predictionTruePositivesJson;

    public DocumentTypeTruePositive() {
    }

	
    public DocumentTypeTruePositive(Document document, PredictionEvaluation predictionEvaluation, Server server, ServerVersion serverVersion, Type typeByPredictionTypeId, Type typeByGoldTypeId, User user) {
        this.document = document;
        this.predictionEvaluation = predictionEvaluation;
        this.server = server;
        this.serverVersion = serverVersion;
        this.typeByPredictionTypeId = typeByPredictionTypeId;
        this.typeByGoldTypeId = typeByGoldTypeId;
        this.user = user;
    }
    public DocumentTypeTruePositive(Document document, PredictionEvaluation predictionEvaluation, Server server, ServerVersion serverVersion, Type typeByPredictionTypeId, Type typeByGoldTypeId, User user, Integer truePositives, String goldTruePositivesJson, String predictionTruePositivesJson) {
       this.document = document;
       this.predictionEvaluation = predictionEvaluation;
       this.server = server;
       this.serverVersion = serverVersion;
       this.typeByPredictionTypeId = typeByPredictionTypeId;
       this.typeByGoldTypeId = typeByGoldTypeId;
       this.user = user;
       this.truePositives = truePositives;
       this.goldTruePositivesJson = goldTruePositivesJson;
       this.predictionTruePositivesJson = predictionTruePositivesJson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_id", nullable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prediction_evaluation_id", nullable=false)
    public PredictionEvaluation getPredictionEvaluation() {
        return this.predictionEvaluation;
    }
    
    public void setPredictionEvaluation(PredictionEvaluation predictionEvaluation) {
        this.predictionEvaluation = predictionEvaluation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_id", nullable=false)
    public Server getServer() {
        return this.server;
    }
    
    public void setServer(Server server) {
        this.server = server;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_version_id", nullable=false)
    public ServerVersion getServerVersion() {
        return this.serverVersion;
    }
    
    public void setServerVersion(ServerVersion serverVersion) {
        this.serverVersion = serverVersion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prediction_type_id", nullable=false)
    public Type getTypeByPredictionTypeId() {
        return this.typeByPredictionTypeId;
    }
    
    public void setTypeByPredictionTypeId(Type typeByPredictionTypeId) {
        this.typeByPredictionTypeId = typeByPredictionTypeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gold_type_id", nullable=false)
    public Type getTypeByGoldTypeId() {
        return this.typeByGoldTypeId;
    }
    
    public void setTypeByGoldTypeId(Type typeByGoldTypeId) {
        this.typeByGoldTypeId = typeByGoldTypeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="true_positives")
    public Integer getTruePositives() {
        return this.truePositives;
    }
    
    public void setTruePositives(Integer truePositives) {
        this.truePositives = truePositives;
    }

    
    @Column(name="gold_true_positives_json")
    public String getGoldTruePositivesJson() {
        return this.goldTruePositivesJson;
    }
    
    public void setGoldTruePositivesJson(String goldTruePositivesJson) {
        this.goldTruePositivesJson = goldTruePositivesJson;
    }

    
    @Column(name="prediction_true_positives_json")
    public String getPredictionTruePositivesJson() {
        return this.predictionTruePositivesJson;
    }
    
    public void setPredictionTruePositivesJson(String predictionTruePositivesJson) {
        this.predictionTruePositivesJson = predictionTruePositivesJson;
    }




}


