package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DocumentTypeFalsePositive generated by hbm2java
 */
@Entity
@Table(name="document_type_false_positive"
    ,catalog="metaserver2"
    , uniqueConstraints = @UniqueConstraint(columnNames={"prediction_evaluation_id", "server_version_id", "server_id", "user_id", "type_id", "document_id"}) 
)
public class DocumentTypeFalsePositive  implements java.io.Serializable {


     private Integer id;
     private Document document;
     private PredictionEvaluation predictionEvaluation;
     private Server server;
     private ServerVersion serverVersion;
     private Type type;
     private User user;
     private Integer falsePositives;
     private String falsePositivesJson;

    public DocumentTypeFalsePositive() {
    }

	
    public DocumentTypeFalsePositive(Document document, PredictionEvaluation predictionEvaluation, Server server, ServerVersion serverVersion, Type type, User user) {
        this.document = document;
        this.predictionEvaluation = predictionEvaluation;
        this.server = server;
        this.serverVersion = serverVersion;
        this.type = type;
        this.user = user;
    }
    public DocumentTypeFalsePositive(Document document, PredictionEvaluation predictionEvaluation, Server server, ServerVersion serverVersion, Type type, User user, Integer falsePositives, String falsePositivesJson) {
       this.document = document;
       this.predictionEvaluation = predictionEvaluation;
       this.server = server;
       this.serverVersion = serverVersion;
       this.type = type;
       this.user = user;
       this.falsePositives = falsePositives;
       this.falsePositivesJson = falsePositivesJson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_id", nullable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prediction_evaluation_id", nullable=false)
    public PredictionEvaluation getPredictionEvaluation() {
        return this.predictionEvaluation;
    }
    
    public void setPredictionEvaluation(PredictionEvaluation predictionEvaluation) {
        this.predictionEvaluation = predictionEvaluation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_id", nullable=false)
    public Server getServer() {
        return this.server;
    }
    
    public void setServer(Server server) {
        this.server = server;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_version_id", nullable=false)
    public ServerVersion getServerVersion() {
        return this.serverVersion;
    }
    
    public void setServerVersion(ServerVersion serverVersion) {
        this.serverVersion = serverVersion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="false_positives")
    public Integer getFalsePositives() {
        return this.falsePositives;
    }
    
    public void setFalsePositives(Integer falsePositives) {
        this.falsePositives = falsePositives;
    }

    
    @Column(name="false_positives_json")
    public String getFalsePositivesJson() {
        return this.falsePositivesJson;
    }
    
    public void setFalsePositivesJson(String falsePositivesJson) {
        this.falsePositivesJson = falsePositivesJson;
    }




}


