package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,catalog="metaserver2"
)
public class Event  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Date startDate;
     private Date finishDate;
     private boolean sendEmail;
     private Set<Competition> competitions = new HashSet<Competition>(0);

    public Event() {
    }

	
    public Event(String name, String description, Date startDate, boolean sendEmail) {
        this.name = name;
        this.description = description;
        this.startDate = startDate;
        this.sendEmail = sendEmail;
    }
    public Event(String name, String description, Date startDate, Date finishDate, boolean sendEmail, Set<Competition> competitions) {
       this.name = name;
       this.description = description;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.sendEmail = sendEmail;
       this.competitions = competitions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="finish_date", length=19)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    
    @Column(name="send_email", nullable=false)
    public boolean isSendEmail() {
        return this.sendEmail;
    }
    
    public void setSendEmail(boolean sendEmail) {
        this.sendEmail = sendEmail;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="competition_event", catalog="metaserver2", joinColumns = { 
        @JoinColumn(name="event_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="competition_id", nullable=false, updatable=false) })
    public Set<Competition> getCompetitions() {
        return this.competitions;
    }
    
    public void setCompetitions(Set<Competition> competitions) {
        this.competitions = competitions;
    }




}


