package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    ,catalog="metaserver2"
)
public class Permission  implements java.io.Serializable {


     private Integer id;
     private Acos acos;
     private Aros aros;
     private String create;
     private String read;
     private String update;
     private String delete;

    public Permission() {
    }

    public Permission(Acos acos, Aros aros, String create, String read, String update, String delete) {
       this.acos = acos;
       this.aros = aros;
       this.create = create;
       this.read = read;
       this.update = update;
       this.delete = delete;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aco_id", nullable=false)
    public Acos getAcos() {
        return this.acos;
    }
    
    public void setAcos(Acos acos) {
        this.acos = acos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aro_id", nullable=false)
    public Aros getAros() {
        return this.aros;
    }
    
    public void setAros(Aros aros) {
        this.aros = aros;
    }

    
    @Column(name="_create", nullable=false, length=2)
    public String getCreate() {
        return this.create;
    }
    
    public void setCreate(String create) {
        this.create = create;
    }

    
    @Column(name="_read", nullable=false, length=2)
    public String getRead() {
        return this.read;
    }
    
    public void setRead(String read) {
        this.read = read;
    }

    
    @Column(name="_update", nullable=false, length=2)
    public String getUpdate() {
        return this.update;
    }
    
    public void setUpdate(String update) {
        this.update = update;
    }

    
    @Column(name="_delete", nullable=false, length=2)
    public String getDelete() {
        return this.delete;
    }
    
    public void setDelete(String delete) {
        this.delete = delete;
    }




}


