package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrivateDocumentTypeFalsePositive generated by hbm2java
 */
@Entity
@Table(name="private_document_type_false_positive"
    ,catalog="metaserver2"
    , uniqueConstraints = @UniqueConstraint(columnNames={"document_id", "type_id", "private_prediction_evaluation_id"}) 
)
public class PrivateDocumentTypeFalsePositive  implements java.io.Serializable {


     private Integer id;
     private Document document;
     private PrivatePredictionEvaluation privatePredictionEvaluation;
     private Type type;
     private Integer falsePositives;
     private String falsePositivesJson;

    public PrivateDocumentTypeFalsePositive() {
    }

	
    public PrivateDocumentTypeFalsePositive(Document document, PrivatePredictionEvaluation privatePredictionEvaluation, Type type) {
        this.document = document;
        this.privatePredictionEvaluation = privatePredictionEvaluation;
        this.type = type;
    }
    public PrivateDocumentTypeFalsePositive(Document document, PrivatePredictionEvaluation privatePredictionEvaluation, Type type, Integer falsePositives, String falsePositivesJson) {
       this.document = document;
       this.privatePredictionEvaluation = privatePredictionEvaluation;
       this.type = type;
       this.falsePositives = falsePositives;
       this.falsePositivesJson = falsePositivesJson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_id", nullable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="private_prediction_evaluation_id", nullable=false)
    public PrivatePredictionEvaluation getPrivatePredictionEvaluation() {
        return this.privatePredictionEvaluation;
    }
    
    public void setPrivatePredictionEvaluation(PrivatePredictionEvaluation privatePredictionEvaluation) {
        this.privatePredictionEvaluation = privatePredictionEvaluation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

    
    @Column(name="false_positives")
    public Integer getFalsePositives() {
        return this.falsePositives;
    }
    
    public void setFalsePositives(Integer falsePositives) {
        this.falsePositives = falsePositives;
    }

    
    @Column(name="false_positives_json")
    public String getFalsePositivesJson() {
        return this.falsePositivesJson;
    }
    
    public void setFalsePositivesJson(String falsePositivesJson) {
        this.falsePositivesJson = falsePositivesJson;
    }




}


