package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrivateTypePredictionEvaluation generated by hbm2java
 */
@Entity
@Table(name="private_type_prediction_evaluation"
    ,catalog="metaserver2"
    , uniqueConstraints = @UniqueConstraint(columnNames={"private_prediction_evaluation_id", "type_id"}) 
)
public class PrivateTypePredictionEvaluation  implements java.io.Serializable {


     private Integer id;
     private PrivatePredictionEvaluation privatePredictionEvaluation;
     private Type type;
     private Integer exactTruePositives;
     private Integer exactFalsePositives;
     private Integer exactFalseNegatives;
     private Integer truePositives;
     private Integer falsePositives;
     private Integer falseNegatives;
     private Float FScore;
     private Float precision;
     private Float recall;
     private String predictionTruePositivesJson;
     private String goldTruePositivesJson;
     private String falsePositivesJson;
     private String falseNegativesJson;

    public PrivateTypePredictionEvaluation() {
    }

	
    public PrivateTypePredictionEvaluation(PrivatePredictionEvaluation privatePredictionEvaluation, Type type) {
        this.privatePredictionEvaluation = privatePredictionEvaluation;
        this.type = type;
    }
    public PrivateTypePredictionEvaluation(PrivatePredictionEvaluation privatePredictionEvaluation, Type type, Integer exactTruePositives, Integer exactFalsePositives, Integer exactFalseNegatives, Integer truePositives, Integer falsePositives, Integer falseNegatives, Float FScore, Float precision, Float recall, String predictionTruePositivesJson, String goldTruePositivesJson, String falsePositivesJson, String falseNegativesJson) {
       this.privatePredictionEvaluation = privatePredictionEvaluation;
       this.type = type;
       this.exactTruePositives = exactTruePositives;
       this.exactFalsePositives = exactFalsePositives;
       this.exactFalseNegatives = exactFalseNegatives;
       this.truePositives = truePositives;
       this.falsePositives = falsePositives;
       this.falseNegatives = falseNegatives;
       this.FScore = FScore;
       this.precision = precision;
       this.recall = recall;
       this.predictionTruePositivesJson = predictionTruePositivesJson;
       this.goldTruePositivesJson = goldTruePositivesJson;
       this.falsePositivesJson = falsePositivesJson;
       this.falseNegativesJson = falseNegativesJson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="private_prediction_evaluation_id", nullable=false)
    public PrivatePredictionEvaluation getPrivatePredictionEvaluation() {
        return this.privatePredictionEvaluation;
    }
    
    public void setPrivatePredictionEvaluation(PrivatePredictionEvaluation privatePredictionEvaluation) {
        this.privatePredictionEvaluation = privatePredictionEvaluation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

    
    @Column(name="exact_true_positives")
    public Integer getExactTruePositives() {
        return this.exactTruePositives;
    }
    
    public void setExactTruePositives(Integer exactTruePositives) {
        this.exactTruePositives = exactTruePositives;
    }

    
    @Column(name="exact_false_positives")
    public Integer getExactFalsePositives() {
        return this.exactFalsePositives;
    }
    
    public void setExactFalsePositives(Integer exactFalsePositives) {
        this.exactFalsePositives = exactFalsePositives;
    }

    
    @Column(name="exact_false_negatives")
    public Integer getExactFalseNegatives() {
        return this.exactFalseNegatives;
    }
    
    public void setExactFalseNegatives(Integer exactFalseNegatives) {
        this.exactFalseNegatives = exactFalseNegatives;
    }

    
    @Column(name="true_positives")
    public Integer getTruePositives() {
        return this.truePositives;
    }
    
    public void setTruePositives(Integer truePositives) {
        this.truePositives = truePositives;
    }

    
    @Column(name="false_positives")
    public Integer getFalsePositives() {
        return this.falsePositives;
    }
    
    public void setFalsePositives(Integer falsePositives) {
        this.falsePositives = falsePositives;
    }

    
    @Column(name="false_negatives")
    public Integer getFalseNegatives() {
        return this.falseNegatives;
    }
    
    public void setFalseNegatives(Integer falseNegatives) {
        this.falseNegatives = falseNegatives;
    }

    
    @Column(name="f_score", precision=12, scale=0)
    public Float getFScore() {
        return this.FScore;
    }
    
    public void setFScore(Float FScore) {
        this.FScore = FScore;
    }

    
    @Column(name="precision", precision=12, scale=0)
    public Float getPrecision() {
        return this.precision;
    }
    
    public void setPrecision(Float precision) {
        this.precision = precision;
    }

    
    @Column(name="recall", precision=12, scale=0)
    public Float getRecall() {
        return this.recall;
    }
    
    public void setRecall(Float recall) {
        this.recall = recall;
    }

    
    @Column(name="prediction_true_positives_json")
    public String getPredictionTruePositivesJson() {
        return this.predictionTruePositivesJson;
    }
    
    public void setPredictionTruePositivesJson(String predictionTruePositivesJson) {
        this.predictionTruePositivesJson = predictionTruePositivesJson;
    }

    
    @Column(name="gold_true_positives_json")
    public String getGoldTruePositivesJson() {
        return this.goldTruePositivesJson;
    }
    
    public void setGoldTruePositivesJson(String goldTruePositivesJson) {
        this.goldTruePositivesJson = goldTruePositivesJson;
    }

    
    @Column(name="false_positives_json")
    public String getFalsePositivesJson() {
        return this.falsePositivesJson;
    }
    
    public void setFalsePositivesJson(String falsePositivesJson) {
        this.falsePositivesJson = falsePositivesJson;
    }

    
    @Column(name="false_negatives_json")
    public String getFalseNegativesJson() {
        return this.falseNegativesJson;
    }
    
    public void setFalseNegativesJson(String falseNegativesJson) {
        this.falseNegativesJson = falseNegativesJson;
    }




}


