package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrivateDocumentTypeTruePositive generated by hbm2java
 */
@Entity
@Table(name="private_document_type_true_positive"
    ,catalog="metaserver2"
)
public class PrivateDocumentTypeTruePositive  implements java.io.Serializable {


     private Integer id;
     private Document document;
     private PrivatePredictionEvaluation privatePredictionEvaluation;
     private Type typeByGoldTypeId;
     private Type typeByPredictionTypeId;
     private Integer truePositives;
     private String goldTruePositivesJson;
     private String predictionTruePositivesJson;

    public PrivateDocumentTypeTruePositive() {
    }

	
    public PrivateDocumentTypeTruePositive(Document document, PrivatePredictionEvaluation privatePredictionEvaluation, Type typeByGoldTypeId, Type typeByPredictionTypeId) {
        this.document = document;
        this.privatePredictionEvaluation = privatePredictionEvaluation;
        this.typeByGoldTypeId = typeByGoldTypeId;
        this.typeByPredictionTypeId = typeByPredictionTypeId;
    }
    public PrivateDocumentTypeTruePositive(Document document, PrivatePredictionEvaluation privatePredictionEvaluation, Type typeByGoldTypeId, Type typeByPredictionTypeId, Integer truePositives, String goldTruePositivesJson, String predictionTruePositivesJson) {
       this.document = document;
       this.privatePredictionEvaluation = privatePredictionEvaluation;
       this.typeByGoldTypeId = typeByGoldTypeId;
       this.typeByPredictionTypeId = typeByPredictionTypeId;
       this.truePositives = truePositives;
       this.goldTruePositivesJson = goldTruePositivesJson;
       this.predictionTruePositivesJson = predictionTruePositivesJson;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_id", nullable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="private_prediction_evaluation_id", nullable=false)
    public PrivatePredictionEvaluation getPrivatePredictionEvaluation() {
        return this.privatePredictionEvaluation;
    }
    
    public void setPrivatePredictionEvaluation(PrivatePredictionEvaluation privatePredictionEvaluation) {
        this.privatePredictionEvaluation = privatePredictionEvaluation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gold_type_id", nullable=false)
    public Type getTypeByGoldTypeId() {
        return this.typeByGoldTypeId;
    }
    
    public void setTypeByGoldTypeId(Type typeByGoldTypeId) {
        this.typeByGoldTypeId = typeByGoldTypeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prediction_type_id", nullable=false)
    public Type getTypeByPredictionTypeId() {
        return this.typeByPredictionTypeId;
    }
    
    public void setTypeByPredictionTypeId(Type typeByPredictionTypeId) {
        this.typeByPredictionTypeId = typeByPredictionTypeId;
    }

    
    @Column(name="true_positives")
    public Integer getTruePositives() {
        return this.truePositives;
    }
    
    public void setTruePositives(Integer truePositives) {
        this.truePositives = truePositives;
    }

    
    @Column(name="gold_true_positives_json")
    public String getGoldTruePositivesJson() {
        return this.goldTruePositivesJson;
    }
    
    public void setGoldTruePositivesJson(String goldTruePositivesJson) {
        this.goldTruePositivesJson = goldTruePositivesJson;
    }

    
    @Column(name="prediction_true_positives_json")
    public String getPredictionTruePositivesJson() {
        return this.predictionTruePositivesJson;
    }
    
    public void setPredictionTruePositivesJson(String predictionTruePositivesJson) {
        this.predictionTruePositivesJson = predictionTruePositivesJson;
    }




}


