package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectConsensus generated by hbm2java
 */
@Entity
@Table(name="project_consensus"
    ,catalog="metaserver2"
)
public class ProjectConsensus  implements java.io.Serializable {


     private Integer id;
     private Document document;
     private Project project;
     private Type type;
     private Integer annotatedText;
     private Integer init;
     private Integer end;
     private Integer section;

    public ProjectConsensus() {
    }

	
    public ProjectConsensus(Document document, Project project, Type type) {
        this.document = document;
        this.project = project;
        this.type = type;
    }
    public ProjectConsensus(Document document, Project project, Type type, Integer annotatedText, Integer init, Integer end, Integer section) {
       this.document = document;
       this.project = project;
       this.type = type;
       this.annotatedText = annotatedText;
       this.init = init;
       this.end = end;
       this.section = section;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_id", nullable=false)
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

    
    @Column(name="annotated_text")
    public Integer getAnnotatedText() {
        return this.annotatedText;
    }
    
    public void setAnnotatedText(Integer annotatedText) {
        this.annotatedText = annotatedText;
    }

    
    @Column(name="init")
    public Integer getInit() {
        return this.init;
    }
    
    public void setInit(Integer init) {
        this.init = init;
    }

    
    @Column(name="end")
    public Integer getEnd() {
        return this.end;
    }
    
    public void setEnd(Integer end) {
        this.end = end;
    }

    
    @Column(name="section")
    public Integer getSection() {
        return this.section;
    }
    
    public void setSection(Integer section) {
        this.section = section;
    }




}


