package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestEvaluation generated by hbm2java
 */
@Entity
@Table(name="request_evaluation"
    ,catalog="metaserver2"
)
public class RequestEvaluation  implements java.io.Serializable {


     private Integer id;
     private Date created;
     private String name;
     private Boolean isPrivate;
     private Boolean allDocuments;
     private Set<ScheduleRequest> scheduleRequests = new HashSet<ScheduleRequest>(0);
     private Set<Server> servers = new HashSet<Server>(0);

    public RequestEvaluation() {
    }

    public RequestEvaluation(Date created, String name, Boolean isPrivate, Boolean allDocuments, Set<ScheduleRequest> scheduleRequests, Set<Server> servers) {
       this.created = created;
       this.name = name;
       this.isPrivate = isPrivate;
       this.allDocuments = allDocuments;
       this.scheduleRequests = scheduleRequests;
       this.servers = servers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="name", length=2000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="is_private")
    public Boolean getIsPrivate() {
        return this.isPrivate;
    }
    
    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    
    @Column(name="all_documents")
    public Boolean getAllDocuments() {
        return this.allDocuments;
    }
    
    public void setAllDocuments(Boolean allDocuments) {
        this.allDocuments = allDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requestEvaluation")
    public Set<ScheduleRequest> getScheduleRequests() {
        return this.scheduleRequests;
    }
    
    public void setScheduleRequests(Set<ScheduleRequest> scheduleRequests) {
        this.scheduleRequests = scheduleRequests;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="request_evaluation_server", catalog="metaserver2", joinColumns = { 
        @JoinColumn(name="request_evaluation_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="server_id", nullable=false, updatable=false) })
    public Set<Server> getServers() {
        return this.servers;
    }
    
    public void setServers(Set<Server> servers) {
        this.servers = servers;
    }




}


