package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScheduleAlgorithm generated by hbm2java
 */
@Entity
@Table(name="schedule_algorithm"
    ,catalog="metaserver2"
)
public class ScheduleAlgorithm  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<ScheduleRequest> scheduleRequests = new HashSet<ScheduleRequest>(0);

    public ScheduleAlgorithm() {
    }

    public ScheduleAlgorithm(String name, String description, Set<ScheduleRequest> scheduleRequests) {
       this.name = name;
       this.description = description;
       this.scheduleRequests = scheduleRequests;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="scheduleAlgorithm")
    public Set<ScheduleRequest> getScheduleRequests() {
        return this.scheduleRequests;
    }
    
    public void setScheduleRequests(Set<ScheduleRequest> scheduleRequests) {
        this.scheduleRequests = scheduleRequests;
    }




}


