package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServerNormalization generated by hbm2java
 */
@Entity
@Table(name="server_normalization"
    ,catalog="metaserver2"
)
public class ServerNormalization  implements java.io.Serializable {


     private Integer id;
     private Server server;
     private Type type;
     private String database;
     private Boolean isOfficial;

    public ServerNormalization() {
    }

	
    public ServerNormalization(Server server, Type type, String database) {
        this.server = server;
        this.type = type;
        this.database = database;
    }
    public ServerNormalization(Server server, Type type, String database, Boolean isOfficial) {
       this.server = server;
       this.type = type;
       this.database = database;
       this.isOfficial = isOfficial;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_id", nullable=false)
    public Server getServer() {
        return this.server;
    }
    
    public void setServer(Server server) {
        this.server = server;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

    
    @Column(name="database", nullable=false, length=254)
    public String getDatabase() {
        return this.database;
    }
    
    public void setDatabase(String database) {
        this.database = database;
    }

    
    @Column(name="is_official")
    public Boolean getIsOfficial() {
        return this.isOfficial;
    }
    
    public void setIsOfficial(Boolean isOfficial) {
        this.isOfficial = isOfficial;
    }




}


