package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServerConnectionLog generated by hbm2java
 */
@Entity
@Table(name="server_connection_log"
    ,catalog="metaserver2"
)
public class ServerConnectionLog  implements java.io.Serializable {


     private Integer id;
     private Server server;
     private String requestBody;
     private String responseBody;
     private String exception;
     private Date created;
     private Boolean revised;
     private String exceptionName;
     private Integer exceptionId;

    public ServerConnectionLog() {
    }

	
    public ServerConnectionLog(Server server) {
        this.server = server;
    }
    public ServerConnectionLog(Server server, String requestBody, String responseBody, String exception, Date created, Boolean revised, String exceptionName, Integer exceptionId) {
       this.server = server;
       this.requestBody = requestBody;
       this.responseBody = responseBody;
       this.exception = exception;
       this.created = created;
       this.revised = revised;
       this.exceptionName = exceptionName;
       this.exceptionId = exceptionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="server_id", nullable=false)
    public Server getServer() {
        return this.server;
    }
    
    public void setServer(Server server) {
        this.server = server;
    }

    
    @Column(name="request_body")
    public String getRequestBody() {
        return this.requestBody;
    }
    
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    
    @Column(name="response_body")
    public String getResponseBody() {
        return this.responseBody;
    }
    
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    
    @Column(name="exception", length=65535)
    public String getException() {
        return this.exception;
    }
    
    public void setException(String exception) {
        this.exception = exception;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="revised")
    public Boolean getRevised() {
        return this.revised;
    }
    
    public void setRevised(Boolean revised) {
        this.revised = revised;
    }

    
    @Column(name="exception_name")
    public String getExceptionName() {
        return this.exceptionName;
    }
    
    public void setExceptionName(String exceptionName) {
        this.exceptionName = exceptionName;
    }

    
    @Column(name="exception_id")
    public Integer getExceptionId() {
        return this.exceptionId;
    }
    
    public void setExceptionId(Integer exceptionId) {
        this.exceptionId = exceptionId;
    }




}


