package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Subscriptor generated by hbm2java
 */
@Entity
@Table(name="subscriptor"
    ,catalog="metaserver2"
    , uniqueConstraints = @UniqueConstraint(columnNames="key") 
)
public class Subscriptor  implements java.io.Serializable {


     private Integer id;
     private String key;
     private String name;
     private String email;
     private String information;
     private Date created;
     private Boolean confirmed;
     private String organization;
     private Set<Newsletter> newsletters = new HashSet<Newsletter>(0);

    public Subscriptor() {
    }

    public Subscriptor(String key, String name, String email, String information, Date created, Boolean confirmed, String organization, Set<Newsletter> newsletters) {
       this.key = key;
       this.name = name;
       this.email = email;
       this.information = information;
       this.created = created;
       this.confirmed = confirmed;
       this.organization = organization;
       this.newsletters = newsletters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="key", unique=true, length=40)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="name", length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=500)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="information", length=65535)
    public String getInformation() {
        return this.information;
    }
    
    public void setInformation(String information) {
        this.information = information;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="confirmed")
    public Boolean getConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    
    @Column(name="organization", length=500)
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="newsletter_subscriptor", catalog="metaserver2", joinColumns = { 
        @JoinColumn(name="subscriptor_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="newsletter_id", nullable=false, updatable=false) })
    public Set<Newsletter> getNewsletters() {
        return this.newsletters;
    }
    
    public void setNewsletters(Set<Newsletter> newsletters) {
        this.newsletters = newsletters;
    }




}


