package generador.de.modelos;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserConnection generated by hbm2java
 */
@Entity
@Table(name="user_connection"
    ,catalog="metaserver2"
)
public class UserConnection  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date created;
     private Date sessionTime;
     private String country;
     private String city;
     private String ip;
     private String loc;

    public UserConnection() {
    }

	
    public UserConnection(User user, Date created) {
        this.user = user;
        this.created = created;
    }
    public UserConnection(User user, Date created, Date sessionTime, String country, String city, String ip, String loc) {
       this.user = user;
       this.created = created;
       this.sessionTime = sessionTime;
       this.country = country;
       this.city = city;
       this.ip = ip;
       this.loc = loc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="session_time", length=8)
    public Date getSessionTime() {
        return this.sessionTime;
    }
    
    public void setSessionTime(Date sessionTime) {
        this.sessionTime = sessionTime;
    }

    
    @Column(name="country", length=200)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="city", length=200)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="ip", length=50)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="loc", length=200)
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }




}


