package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DocumentProviderEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "document_provider", catalog = "")
public class DocumentProviderEntity implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    @Column(name = "name", nullable = false)
    private String name;
    @Column(name = "url", length = 65535)
    private String url;
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "schedule_request_document_provider", catalog = "metaserver2", joinColumns = {
            @JoinColumn(name = "document_provider_id", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "schedule_request_id", nullable = false, updatable = false)})
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "documentProviders"})
    private Set<ScheduleRequestEntity> scheduleRequests = new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "documentProvider")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "documentProvider"})
    private Set<DocumentEntity> documents = new HashSet<>(0);


}


