package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PredictionResponseEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "prediction_response", catalog = "")
public class PredictionResponseEntity implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;



    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    private Date created;
    @Temporal(TemporalType.TIME)
    @Column(name = "execution_time", nullable = false, length = 8)
    private Date executionTime;
    @Column(name = "documents_json")
    private String documentsJson;
    @Column(name = "number_of_documents_recived")
    private Integer numberOfDocumentsRecived;
    @Column(name = "number_of_predictions")
    private Integer numberOfPredictions;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prediction_request_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "predictionResponses"})
    private PredictionRequestEntity predictionRequest;
}


