package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PredictionUploadEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "prediction_upload", catalog = "")
public class PredictionUploadEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "competition_id", nullable = false)
//    private Competition competition;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private UserEntity user;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 19)
    private Date created;
    @Column(name = "file", nullable = false)
    private byte[] file;
    @Column(name = "extension", nullable = false, length = 10)
    private String extension;
    @Column(name = "size", nullable = false)
    private int size;
    @Column(name = "name", nullable = false, length = 65535)
    private String name;

    @Column(name = "is_final_submission")
    private Boolean isFinalSubmission;
    @Column(name = "is_loaded")
    private Boolean isLoaded;
    @Column(name = "is_hidden")
    private Boolean isHidden;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "predictionUpload")
    private Set<PrivatePredictionEvaluationEntity> privatePredictionEvaluations = new HashSet<>(0);
    //    @OneToMany(fetch = FetchType.LAZY, mappedBy = "predictionUpload")
//    private Set<CompetitionParticipant> competitionParticipants = new HashSet<CompetitionParticipant>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "predictionUpload")
    private Set<PrivatePredictionEntity> privatePredictions = new HashSet<>(0);


}


