package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RolEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "rol", catalog = "metaserver2")
public class RolEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    @Column(name = "name", nullable = false, length = 500)
    private String name;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "rol"})
    private Set<UserEntity> users = new HashSet<>(0);

}


