package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ServerStateEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "server_state", catalog = "metaserver2")
public class ServerStateEntity implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "server_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "serverStates"})
    private ServerEntity server;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "server_state_name_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "serverStates"})
    private ServerStateNameEntity serverStateName;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    private Date created;
    @Column(name = "retrieved_version", length = 500)
    private String retrievedVersion;
    @Column(name = "max_analyzable_documents")
    private Integer maxAnalyzableDocuments;
    @Column(name = "response_time", precision = 12, scale = 0)
    private Float responseTime;
    @Column(name = "is_private")
    private Boolean isPrivate;

}


