package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ServerStateNameEntity generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name = "server_state_name", catalog = "metaserver2", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class ServerStateNameEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    @Column(name = "name", unique = true, nullable = false)
    private String name;
    @Column(name = "description", length = 65535)
    private String description;
    @Column(name = "color", length = 15)
    private String color;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "serverStateName")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "serverStateName"})
    private Set<ServerStateEntity> serverStates = new HashSet<>(0);


}


