package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TaskNameEntity generated by hbm2java
 */
@Entity
@Table(name = "task_name"
        , catalog = "metaserver2"
)
public class TaskNameEntity implements java.io.Serializable {


    private Integer id;
    private String name;
    private String description;
    private Set<TaskEntity> taskEntities = new HashSet<TaskEntity>(0);

    public TaskNameEntity() {
    }

    public TaskNameEntity(String name, String description, Set<TaskEntity> taskEntities) {
        this.name = name;
        this.description = description;
        this.taskEntities = taskEntities;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name = "name", length = 500)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taskName")
    public Set<TaskEntity> getTaskEntities() {
        return this.taskEntities;
    }

    public void setTaskEntities(Set<TaskEntity> taskEntities) {
        this.taskEntities = taskEntities;
    }


}


