package es.uvigo.esei.sgvilar.berest.entities;
// Generated 12-mar-2019 17:18:59 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TaskEntity generated by hbm2java
 */
@Entity
@Table(name = "task"
        , catalog = "metaserver2"
)
public class TaskEntity implements java.io.Serializable {


    private Integer id;
    private TaskNameEntity taskNameEntity;
    private TaskStateEntity taskStateEntity;
    private Date created;
    private Date modified;
    private Date finished;
    private String exception;
    private String description;
    private Float progress;
    private Integer secondsInQueue;
    private String arguments;
    private Set<CompetitionBenchmark> competitionBenchmarks = new HashSet<CompetitionBenchmark>(0);
    private Set<JobQueue> jobQueues = new HashSet<JobQueue>(0);
    private Set<PredictionRequest> predictionRequests = new HashSet<PredictionRequest>(0);
    private Set<PrivatePredictionEvaluation> privatePredictionEvaluations = new HashSet<PrivatePredictionEvaluation>(0);

    public TaskEntity() {
    }


    public TaskEntity(TaskNameEntity taskNameEntity, TaskStateEntity taskStateEntity) {
        this.taskNameEntity = taskNameEntity;
        this.taskStateEntity = taskStateEntity;
    }

    public TaskEntity(TaskNameEntity taskNameEntity, TaskStateEntity taskStateEntity, Date created, Date modified, Date finished, String exception, String description, Float progress, Integer secondsInQueue, String arguments, Set<CompetitionBenchmark> competitionBenchmarks, Set<JobQueue> jobQueues, Set<PredictionRequest> predictionRequests, Set<PrivatePredictionEvaluation> privatePredictionEvaluations) {
        this.taskNameEntity = taskNameEntity;
        this.taskStateEntity = taskStateEntity;
        this.created = created;
        this.modified = modified;
        this.finished = finished;
        this.exception = exception;
        this.description = description;
        this.progress = progress;
        this.secondsInQueue = secondsInQueue;
        this.arguments = arguments;
        this.competitionBenchmarks = competitionBenchmarks;
        this.jobQueues = jobQueues;
        this.predictionRequests = predictionRequests;
        this.privatePredictionEvaluations = privatePredictionEvaluations;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_name_id", nullable = false)
    public TaskNameEntity getTaskNameEntity() {
        return this.taskNameEntity;
    }

    public void setTaskNameEntity(TaskNameEntity taskNameEntity) {
        this.taskNameEntity = taskNameEntity;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_state_id", nullable = false)
    public TaskStateEntity getTaskStateEntity() {
        return this.taskStateEntity;
    }

    public void setTaskStateEntity(TaskStateEntity taskStateEntity) {
        this.taskStateEntity = taskStateEntity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modified", length = 19)
    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "finished", length = 19)
    public Date getFinished() {
        return this.finished;
    }

    public void setFinished(Date finished) {
        this.finished = finished;
    }


    @Column(name = "exception", length = 65535)
    public String getException() {
        return this.exception;
    }

    public void setException(String exception) {
        this.exception = exception;
    }


    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "progress", precision = 12, scale = 0)
    public Float getProgress() {
        return this.progress;
    }

    public void setProgress(Float progress) {
        this.progress = progress;
    }


    @Column(name = "seconds_in_queue")
    public Integer getSecondsInQueue() {
        return this.secondsInQueue;
    }

    public void setSecondsInQueue(Integer secondsInQueue) {
        this.secondsInQueue = secondsInQueue;
    }


    @Column(name = "arguments", length = 65535)
    public String getArguments() {
        return this.arguments;
    }

    public void setArguments(String arguments) {
        this.arguments = arguments;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
    public Set<CompetitionBenchmark> getCompetitionBenchmarks() {
        return this.competitionBenchmarks;
    }

    public void setCompetitionBenchmarks(Set<CompetitionBenchmark> competitionBenchmarks) {
        this.competitionBenchmarks = competitionBenchmarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
    public Set<JobQueue> getJobQueues() {
        return this.jobQueues;
    }

    public void setJobQueues(Set<JobQueue> jobQueues) {
        this.jobQueues = jobQueues;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
    public Set<PredictionRequest> getPredictionRequests() {
        return this.predictionRequests;
    }

    public void setPredictionRequests(Set<PredictionRequest> predictionRequests) {
        this.predictionRequests = predictionRequests;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
    public Set<PrivatePredictionEvaluation> getPrivatePredictionEvaluations() {
        return this.privatePredictionEvaluations;
    }

    public void setPrivatePredictionEvaluations(Set<PrivatePredictionEvaluation> privatePredictionEvaluations) {
        this.privatePredictionEvaluations = privatePredictionEvaluations;
    }


}


